language: node_js

node_js:
- stable

before_script:
- git config --global user.email "ktyacke@gmail.com"
- git config --global user.name "Kyle Tyacke"
- npm install -g jscs

script:
- jscs src

before_deploy:
- npm version patch

deploy:
  provider: npm
  email: ktyacke@gmail.com
  api_key:
    secure: dsGLSutR6PLAWc0iXsm9E43RLfSziaShvcLOPxiAg6yPrTYIQBBr04q8uOxCh7onfm+2b/WIoAazwiPpR2Dt8PHPJQP3q2B8KxjD8EJXYAAKTAW78fdd3QnUchHUatYCcH1JQBiFwvuiU2Za2jnZ3jzQxUyoMU/eshCBPWJ8MtrazrNjhRvMnZi8xY+QO3NFCGwxSclCm0e6170r2PEvBfVhofXHYKPIMj7fFPzoHZqqFMbcZPNsMZoPYAj58EZ1tmgLGvQW+MBcVGFsDREbeqFCt37sRvQwnEyHhOrsBfshQjPDyh4RFgGncJotIPli52JS49Z+3Dhzt7wjWSLpdsS8nQJS8IwNDf+RCFGgL7nP5KnV/1Vs7GDzrX+PS9dpUZ3uALslYUo6M59pmAaxx1R1dECQDEJHkwz+EAbaRzsm+jeTL6dohxDnBrF3QMq/JZipC/a+pwtQ436Q4uNg8ctKD1WRItbBGbgOTmKAm1lfhe4R59BrCZKoF0f55rsPAqAS2N+KNy8YW9lG1UU7JUjasisqc9+E3qxcYMzya+zoa2Gmruk1uXVGq2VVriSgkymTRif6RsYr3PNRMDk0gNPGQORK1Y1xw3qROZmRABiT6Y1KltgURumVzqU+qSbOevidEsvKuar3DlOalRcIQeOlXPYRYZuwA7VhW8eanes=
  on:
    repo: ktyacke/travis-node-example

notifications:
  slack:
    on_success: always
    on_failure: always
    on_start: always
    on_pull_requests: true
    secure: s0QcUOb/9yAFgbiAh3Ik8rlI0w5hebssQum9NiOnAsapM9r5uYCdyN/AA2kEwi6R0fp0aXHAMaf0t2zRBSpGUjaXjuo1ZeidG1Ik9Qib9l1A8168k29MqC7UkfbM7C1Jbkxpsm+w9Ul0ehmCROW0gEMw0aNTnwf8ELgKwsgQI12MzKVpzTZQR+RcT+Ia59KfhaSdyGSCSASeVWJEmNv6RR/LIEYfabvoUmRlimD3MQrK41QH77cddfY3kDCmV17Rc+kSNIXraddnMDIlWfCTr26sBavLq1OELSW7NZvEw2AxPpIK9Hx8k8GrCCBP45e0mb+wRMh/mVenVMq+taiOVPP8gogo08hiqCYC1fcZGYjv3XQvm9GweNrl2D9JIbOWSbpwOr7/c7w4QJeBxwKAJiyR9Dd7iVBtXhIMnT710AAgHCAsdHYN2FDn1mMeGx1MZKVrD6TJvafwRrqDsEfsC2+cvaXSlgyV2vwCqHWcPmXVzbDsm9e45nLRh11v21uKk+bgvucU9UvyxIcfbKQL50amhtYPGsf4cmrtqrSdjZVBXqrWwcu/gjSNATowG9xOvfUanaH5O4ijd5f5YHBQwHCmmOXnpuUPfiiYgM6sGoRmrnXkNiKejP33Xr7/EsgZvE9xdueM/iL9LRgTQmdahVcyEYnbBAGuBOLEuLJlk5I=