language: node_js

node_js:
  - stable

services:
  - couchdb

before_script:
  - git config --global user.email "ktyacke@gmail.com"
  - git config --global user.name "Kyle Tyacke"
  - npm install -g jscs
  - curl -X PUT localhost:5984/travis-node-demo
  - curl -X GET http://127.0.0.1:5984/_all_dbs

script:
  - jscs src

before_deploy:
  - npm version patch

deploy:
  provider: npm
  email: ktyacke@gmail.com
  api_key:
    secure: dsGLSutR6PLAWc0iXsm9E43RLfSziaShvcLOPxiAg6yPrTYIQBBr04q8uOxCh7onfm+2b/WIoAazwiPpR2Dt8PHPJQP3q2B8KxjD8EJXYAAKTAW78fdd3QnUchHUatYCcH1JQBiFwvuiU2Za2jnZ3jzQxUyoMU/eshCBPWJ8MtrazrNjhRvMnZi8xY+QO3NFCGwxSclCm0e6170r2PEvBfVhofXHYKPIMj7fFPzoHZqqFMbcZPNsMZoPYAj58EZ1tmgLGvQW+MBcVGFsDREbeqFCt37sRvQwnEyHhOrsBfshQjPDyh4RFgGncJotIPli52JS49Z+3Dhzt7wjWSLpdsS8nQJS8IwNDf+RCFGgL7nP5KnV/1Vs7GDzrX+PS9dpUZ3uALslYUo6M59pmAaxx1R1dECQDEJHkwz+EAbaRzsm+jeTL6dohxDnBrF3QMq/JZipC/a+pwtQ436Q4uNg8ctKD1WRItbBGbgOTmKAm1lfhe4R59BrCZKoF0f55rsPAqAS2N+KNy8YW9lG1UU7JUjasisqc9+E3qxcYMzya+zoa2Gmruk1uXVGq2VVriSgkymTRif6RsYr3PNRMDk0gNPGQORK1Y1xw3qROZmRABiT6Y1KltgURumVzqU+qSbOevidEsvKuar3DlOalRcIQeOlXPYRYZuwA7VhW8eanes=
  on:
    repo: ktyacke/travis-node-example
    branch: master

notifications:
  email:
    recipients:
      - ktyacke@gmail.com
    on_success: always
    on_failure: always

  slack:
    rooms:
      - secure: nBGlmJLAMIc7hACv7+lXlx5UEY0DzvHOUsCDSCzEpvWA41uINkojeKgAjFs1w+nvFEF2ZdhJu2dUXs28guR49qOs0HKBFzjdANlp1YGqz7p+QpQbxGhWdpe8J78+BYz/Axtae2KVfTHjPk+32LZAa2y0Znnv8D7KusjChmDhS0y04g2W5dDGGa8yCFBXrodxZ47cy51ZJo0q+dUUh75tRN1LUpIdtprWpmb9PrxrFtF5pKRTbOu1+r9TtuLDY5TB5BlsAWO34ewioZfdGg2iOdLR1xfq9oCIN8lK+hEFwccj15Olx6HvyGD0q3mrn+jVYUfNpBi/3vInXVaaNdQUl4lH9By+0ixII6x9QjuIEJ83OqboY5289uBvi9YfhiDeTSKJVVygElFrPbEaYmHtPghdJAWpmROcbCHaRPdzy0A0uVSwNPqfRBwmmI5GK6f8o25pG93iJr+foLvoGN2ZE94YwXVT/jKa9QpOX9lcEGr746fKYwyC6inDp4/fVl7C1NYoyzwErPHYVqrBzvNSAfYhczH7ra5BxgZvlWYTNQhspHB2o5NCchxAWW36FLjPnZAg8bX/0b0jnLBLAZt+AyussgI+nfGgYncPWYOiTOnpaG19V9mtqYjSkvf+nMP6rCiElq1FR1xJ+VFPOW4jkbRikInlFhMA7snKpwx7w8w=
    on_success: always
    on_failure: always
    on_start: always
