language: node_js

node_js:
  - stable

services:
  - couchdb

before_script:
  - npm install -g jscs
  - curl -X PUT http://127.0.0.1:5984/travis-node-demo
  - curl -X GET http://127.0.0.1:5984/_all_dbs

script:
  - jscs src
  - mocha
  
