language: node_js
node_js:
- stable
services:
- couchdb
before_script:
- git config --global user.email "ktyacke@gmail.com"
- git config --global user.name "Kyle Tyacke"
- npm install -g jscs
- curl -X PUT http://127.0.0.1:5984/travis-node-demo
- curl -X GET http://127.0.0.1:5984/_all_dbs
script:
- jscs src
deploy:
  provider: npm
  email: ktyacke@gmail.com
  api_key:
    secure: dsGLSutR6PLAWc0iXsm9E43RLfSziaShvcLOPxiAg6yPrTYIQBBr04q8uOxCh7onfm+2b/WIoAazwiPpR2Dt8PHPJQP3q2B8KxjD8EJXYAAKTAW78fdd3QnUchHUatYCcH1JQBiFwvuiU2Za2jnZ3jzQxUyoMU/eshCBPWJ8MtrazrNjhRvMnZi8xY+QO3NFCGwxSclCm0e6170r2PEvBfVhofXHYKPIMj7fFPzoHZqqFMbcZPNsMZoPYAj58EZ1tmgLGvQW+MBcVGFsDREbeqFCt37sRvQwnEyHhOrsBfshQjPDyh4RFgGncJotIPli52JS49Z+3Dhzt7wjWSLpdsS8nQJS8IwNDf+RCFGgL7nP5KnV/1Vs7GDzrX+PS9dpUZ3uALslYUo6M59pmAaxx1R1dECQDEJHkwz+EAbaRzsm+jeTL6dohxDnBrF3QMq/JZipC/a+pwtQ436Q4uNg8ctKD1WRItbBGbgOTmKAm1lfhe4R59BrCZKoF0f55rsPAqAS2N+KNy8YW9lG1UU7JUjasisqc9+E3qxcYMzya+zoa2Gmruk1uXVGq2VVriSgkymTRif6RsYr3PNRMDk0gNPGQORK1Y1xw3qROZmRABiT6Y1KltgURumVzqU+qSbOevidEsvKuar3DlOalRcIQeOlXPYRYZuwA7VhW8eanes=
  on:
    tags: true
    repo: ktyacke/travis-node-example
    all_branches: true
notifications:
  email:
    recipients:
    - ktyacke@gmail.com
    on_success: always
    on_failure: always
  slack:
    secure: G1rjfmNYfCvZV84T17V/yYpSX0wBGcoHQyIbrqCgoJKFpYql07VSBR7JlFLHVfAPT4sViC12ifI59sKFSf5M0+zb7EM6VktqsYX03jn9JiSOV9OlwP+24gNhQ3m5eqqwYbaD9/vSiy6nn+5Io8sl6tZ5UBKmPqLH1xuUnF2OO48oOVjqNJ3adQlwUh6EzY4sF5kgg4luQbRJhgKahJFTJ42saz/rGHPy+XqeivE3zQyLV0yMasURZG8AarajNAIB05QbE9hRX2TA7i5KJa8BJHK5GqUrxVDHw2bT3FB7txd2h6AbO3hPYluo95F6AbNwZmmNMPLkNxDAzG2qXjDatp/aT9g1+Ncyd5pZaTuhPK1Q5k7vOUoJOmYvnkaG7UQkR4GP65qGJNPKkr9RzaLzcvOFZrtbPfmiardeTAuPF6YujydeRH8mao6+o7BimXTydEvXqptOGzCqmvVwAFsPTc9eT9OIRYNmhj8ckdYHgfzUJbTs0MBEP3xPj4JaCBMPgG+rRjNqcWq0pbaMysklFJgAn7AfxljFqSsOWcu0YqbwoTCuJjESYp96RUL/Ky2lQlDA/Ot0Yd1lUZ5i9HW7Z3GyUNE9g18tnedefRnJ3i345i0min7DqPLZBafpBrVhQPbjOO3REfO/KG/eC6i0zbLXsf37iYIL+lXBgMXwTR4=
